# Generated by Django 3.2.8 on 2021-11-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211031_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
